name: ci

on:
  push:
    branches: main

jobs:
  multi-registries:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: |
            ./client/Dockerfile
            ./server/comments/Dockerfile
            ./server/event-bus/Dockerfile
            ./server/moderation/Dockerfile
            ./server/posts/Dockerfile
            ./server/query/Dockerfile
          platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
          push: true
          secrets: |
            SHA=$GITHUB_SHA
          tags: |
            shreyasssk/blog/client:SHA
            shreyasssk/blog/client:latest
            shreyasssk/blog/comments:SHA
            shreyasssk/blog/comments:latest
            shreyasssk/blog/event-bus:SHA
            shreyasssk/blog/event-bus:latest
            shreyasssk/blog/moderation:SHA
            shreyasssk/blog/moderation:latest
            shreyasssk/blog/posts:SHA
            shreyasssk/blog/posts:latest
            shreyasssk/blog/query:SHA
            shreyasssk/blog/query:latest
