name: Docker Hub

on:
  push:
    branches: main

jobs:
  Client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1 
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Building Client
        run: | 
          docker build -t shreyasssk/blog-client:latest ./client
          docker build --cache-from shreyasssk/blog-client:latest -t shreyasssk/blog-client:$GITHUB_SHA ./client
      
      - name: Deploying to Docker Registry
        run: |
          docker push shreyasssk/blog-client:$GITHUB_SHA
          docker push shreyasssk/blog-client:latest
          
  Comments:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1 
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Building Server/Comments
        run: |
          docker build -t shreyasssk/blog-comments:latest ./server/comments
          docker build --cache-from shreyasssk/blog-comments:latest -t shreyasssk/blog-comments:$GITHUB_SHA ./server/comments
      
      - name: Deploying to Docker Registry
        run: |
          docker push shreyasssk/blog-comments:$GITHUB_SHA
          docker push shreyasssk/blog-comments:latest
          
  Event-Bus:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1 
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Building Server/Event-Bus
        run: |
          docker build -t shreyasssk/blog-event-bus:latest ./server/event-bus
          docker build --cache-from shreyasssk/blog-event-bus:latest -t shreyasssk/blog-event-bus:$GITHUB_SHA ./server/event-bus
      
      - name: Deploying to Docker Registry
        run: |
          docker push shreyasssk/blog-event-bus:$GITHUB_SHA
          docker push shreyasssk/blog-event-bus:latest
  
  Moderation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1 
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Building Server/Moderation
        run: |
          docker build -t shreyasssk/blog-moderation:latest ./server/moderation
          docker build --cache-from shreyasssk-blog/moderation -t shreyasssk/blog-moderation:$GITHUB_SHA ./server/moderation
          
      - name: Deploying to Docker Registry
        run: |
          docker push shreyasssk/blog-moderation:$GITHUB_SHA
          docker push shreyasssk/blog-moderation:latest
          
  Posts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1 
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Building Server/Posts
        run: |
          docker build -t shreyasssk/blog-posts:latest ./server/posts
          docker build --cache-from shreyasssk/blog-posts:latest -t shreyasssk/blog-posts:$GITHUB_SHA ./server/posts
          
      - name: Deploying to Docker Registry
        run: |
          docker push shreyasssk/blog-posts:$GITHUB_SHA
          docker push shreyasssk/blog-posts:latest
        
  Query:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1 
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Building Server/Query
        run: |
          docker build -t shreyasssk/blog-query:latest ./server/query
          docker build --cache-from shreyasssk/blog-query:latest -t shreyasssk/blog-query:$GITHUB_SHA ./server/query
          
      - name: Deploying to Docker Registry
        run: |
          docker push shreyasssk/blog-query:$GITHUB_SHA
          docker push shreyasssk/blog-query:latest
